services:
  - type: web
    name: interior-bot
    runtime: python
    repo: https://github.com/YOUR_USERNAME/interior_bot  # замените на ваш репозиторий
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0